"""Unified validation package.

This package contains validation functions for the unified pricing framework.
"""

from .benchmark_registry import (
    BenchmarkCase,
    BenchmarkRegistryError,
    BenchmarkRunResult,
    OracleSpec,
    TolerancePolicy,
    default_benchmark_registry,
    registry_as_dict,
    registry_by_id,
    run_registered_benchmark,
    validate_benchmark_registry,
    write_benchmark_result_json,
    write_registry_json,
)
from .pinares_fixed_price_proxy import (
    PINARES_FAIL_CLOSED_BENCHMARK_ID,
    PINARES_FIXED_PRICE_PROXY_BENCHMARK_ID,
    PINARES_FIXED_PRICE_PROXY_BENCHMARK_IDS,
    PINARES_FIXED_PRICE_PROXY_FIXTURE_ID,
    PINARES_FIXED_PRICE_PROXY_PROBLEM_HASH,
    PINARES_FIXED_PRICE_PROXY_PROBLEM_ID,
    PINARES_FIXED_PRICE_PROXY_ROUTE_ID,
    PINARES_QPS_CONTRACT_BENCHMARK_ID,
    PinaresFixedPriceProxyCase,
    PinaresFixedPriceProxyReport,
    export_public_pinares_fixed_price_proxy_fixture_json,
    public_pinares_fixed_price_problem_spec,
    public_pinares_full_deal_unsupported_problem_spec,
    run_public_pinares_fixed_price_proxy_fixture,
)
from .validators import (
    validate_positive,
    validate_non_negative,
    validate_probability,
    validate_grid_parameters,
    validate_option_parameters,
    validate_model_parameters,
    validate_array,
    validate_spot_price,
)

__all__ = [
    "BenchmarkCase",
    "BenchmarkRegistryError",
    "BenchmarkRunResult",
    "OracleSpec",
    "TolerancePolicy",
    "PINARES_FAIL_CLOSED_BENCHMARK_ID",
    "PINARES_FIXED_PRICE_PROXY_BENCHMARK_ID",
    "PINARES_FIXED_PRICE_PROXY_BENCHMARK_IDS",
    "PINARES_FIXED_PRICE_PROXY_FIXTURE_ID",
    "PINARES_FIXED_PRICE_PROXY_PROBLEM_HASH",
    "PINARES_FIXED_PRICE_PROXY_PROBLEM_ID",
    "PINARES_FIXED_PRICE_PROXY_ROUTE_ID",
    "PINARES_QPS_CONTRACT_BENCHMARK_ID",
    "PinaresFixedPriceProxyCase",
    "PinaresFixedPriceProxyReport",
    "default_benchmark_registry",
    "export_public_pinares_fixed_price_proxy_fixture_json",
    "public_pinares_fixed_price_problem_spec",
    "public_pinares_full_deal_unsupported_problem_spec",
    "registry_as_dict",
    "registry_by_id",
    "run_public_pinares_fixed_price_proxy_fixture",
    "run_registered_benchmark",
    "validate_benchmark_registry",
    "write_benchmark_result_json",
    "write_registry_json",
    "validate_positive",
    "validate_non_negative",
    "validate_probability",
    "validate_grid_parameters",
    "validate_option_parameters",
    "validate_model_parameters",
    "validate_array",
    "validate_spot_price",
]
